[metadata]
name = your-package-name
version = 0.0.0
author = Qingyun Wu
author_email = qingyun@ag2.ai
description = ag2 core
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/qingyun-wu/ag2core
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10

[options.packages.find]
where = src